services:
  - type: web
    name: my-app
    env: python
    python_version: "3.10.11"
    plan: free
    buildCommand: |
      git reset --hard
      git pull origin main
      pip install -r requirements.txt
      pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
      pip install gdown
      gdown --id 1aBrRpA286xEkQXa75zm39biXogiFScEG -O trained_model/model.safetensors
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: ENV_VAR_NAME
        value: "value"
